(() => {
'use strict';
const SUPABASE_URL='https://vogyjohoxerhcjpbifim.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_8QXKs6ZGfecrasgNzQfAjw_beTJIpMg';
const $=s=>document.querySelector(s);
const authPanel=$('[data-auth-panel]'), dashboard=$('[data-dashboard]'), form=$('[data-login-form]'), email=$('#dashboard-email'), status=$('[data-auth-status]'), signout=$('[data-signout]'), refresh=$('[data-refresh]');
let client;
const num=v=>new Intl.NumberFormat('en-US').format(Number(v)||0);
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const date=v=>{try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}catch{return 'UNKNOWN'}};
function showLogin(msg=''){authPanel.hidden=false;dashboard.hidden=true;signout.hidden=true;if(status)status.textContent=msg}
function showDash(user){authPanel.hidden=true;dashboard.hidden=false;signout.hidden=false;$('[data-session-email]').textContent=user?.email||'AUTHENTICATED'}
async function rpc(name,args={}){const {data,error}=await client.rpc(name,args);if(error)throw error;return data}
function set(sel,v){const el=$(sel);if(el)el.textContent=num(v)}
function drawChart(rows){const c=$('[data-traffic-chart]');if(!c)return;const ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||1200,h=300;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const vals=(rows||[]).map(r=>Number(r.visits??r.page_views??r.count??0));const max=Math.max(...vals,1),gap=4,bw=Math.max(3,(w-gap*Math.max(vals.length-1,0))/Math.max(vals.length,1));ctx.strokeStyle='rgba(37,201,216,.18)';ctx.fillStyle='#25c9d8';for(let i=0;i<4;i++){const y=20+i*(h-50)/3;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}vals.forEach((v,i)=>{const bh=(v/max)*(h-55),x=i*(bw+gap),y=h-28-bh;ctx.fillRect(x,y,bw,bh)});ctx.fillStyle='#829093';ctx.font='11px IBM Plex Sans';ctx.fillText('30 DAYS AGO',0,h-7);ctx.fillText('TODAY',Math.max(0,w-42),h-7)}
function renderSources(rows){const el=$('[data-source-list]');if(!el)return;el.innerHTML=(rows||[]).length?(rows||[]).map(r=>`<div class="source-row"><div><strong>${safe(r.source||'direct')}</strong><small>${num(r.visits??r.count)} VISITS</small></div></div>`).join(''):'<p>NO SOURCE DATA RECEIVED.</p>'}
function renderRecent(rows){const el=$('[data-recent-body]');if(!el)return;el.innerHTML=(rows||[]).length?(rows||[]).map(r=>`<tr><td>${safe(date(r.created_at))}</td><td><strong>#${String(Number(r.believer_number)||0).padStart(4,'0')}</strong></td><td class="${r.is_returning?'returning':''}">${r.is_returning?'RETURNING':'NEW'}</td><td>${safe(r.event_type||'page_view')}</td><td>${safe(r.source||'direct')}</td><td>${safe(r.page_path||'/')}</td></tr>`).join(''):'<tr><td colspan="6">NO VISITOR ACTIVITY RECEIVED.</td></tr>'}
async function load(){if(refresh)refresh.disabled=true;try{const [summaryRaw,recent,sources,daily]=await Promise.all([rpc('dashboard_summary'),rpc('dashboard_recent_visitors',{p_limit:50}),rpc('dashboard_traffic_sources'),rpc('dashboard_daily_traffic',{p_days:30})]);const s=Array.isArray(summaryRaw)?(summaryRaw[0]||{}):(summaryRaw||{});set('[data-total-views]',s.total_page_views??s.page_views);set('[data-unique-visitors]',s.unique_visitors??s.total_visitors);set('[data-returning]',s.returning_visits??s.returning_visitors);set('[data-qr]',s.qr_entries??s.qr_scans);set('[data-today]',s.visits_today??s.today);set('[data-seven]',s.last_7_days??s.visits_7_days);set('[data-free4x6-count]',s.free4x6_scans??s.free_4x6_scans);renderSources(sources);renderRecent(recent);drawChart(daily);$('[data-refresh-time]').textContent='UPDATED // '+date(new Date())}catch(e){console.error(e);const msg=e?.message||'DASHBOARD DATA COULD NOT BE LOADED';$('[data-refresh-time]').textContent='ERROR // '+msg}finally{if(refresh)refresh.disabled=false}}
async function handleSession(session){if(!session?.user){showLogin();return}showDash(session.user);await load()}
form?.addEventListener('submit',async e=>{e.preventDefault();const value=email.value.trim();if(!value)return;status.textContent='TRANSMITTING ACCESS REQUEST...';try{const redirectTo=new URL('dashboard.html',window.location.href).href.split('#')[0].split('?')[0];const {error}=await client.auth.signInWithOtp({email:value,options:{emailRedirectTo:redirectTo}});if(error)throw error;status.textContent='ACCESS LINK TRANSMITTED // CHECK YOUR EMAIL.'}catch(err){console.error(err);status.textContent=err.message||'ACCESS REQUEST FAILED.'}});
signout?.addEventListener('click',async()=>{await client.auth.signOut();showLogin('SIGNED OUT.')});refresh?.addEventListener('click',load);window.addEventListener('resize',()=>{if(!dashboard.hidden)load()});
async function init(){if(!window.supabase?.createClient){showLogin('SUPABASE CLIENT DID NOT LOAD.');return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});const {data,error}=await client.auth.getSession();if(error){showLogin(error.message);return}await handleSession(data.session);client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showLogin();else if(session)handleSession(session)})}
init().catch(e=>showLogin(e.message||'SIGNAL CONTROL FAILED TO INITIALIZE.'));
})();