(() => {
'use strict';
const stage=document.querySelector('[data-depth-stage]');if(!stage)return;
const root=document.documentElement,layers=[...document.querySelectorAll('[data-layer]')],clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
function smooth(t){t=clamp(t);return t*t*(3-2*t)}
function render(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=stage.getBoundingClientRect(),travel=Math.max(1,stage.offsetHeight-innerHeight),p=clamp(-r.top/travel);root.style.setProperty('--journey',`${(p*100).toFixed(2)}%`);root.style.setProperty('--p',p.toFixed(4));
layers.forEach(layer=>{const s=Number(layer.dataset.start),e=Number(layer.dataset.end),span=e-s,local=clamp((p-s)/span),fadeIn=smooth(local/.22),fadeOut=1-smooth((local-.78)/.22),opacity=Math.min(fadeIn,fadeOut);layer.style.setProperty('--layer-opacity',opacity.toFixed(3));layer.classList.toggle('active',opacity>.35);layer.style.setProperty('--center-scale',(0.48+local*1.45).toFixed(3));layer.style.setProperty('--fly-scale',(0.38+local*2.6).toFixed(3));layer.style.setProperty('--art-scale',(0.45+local*2.9).toFixed(3));layer.style.setProperty('--side-out',`${local*260}px`);layer.style.setProperty('--portal-scale',(0.25+local*4).toFixed(3));layer.style.setProperty('--frame-scale',(0.28+local*3.6).toFixed(3));layer.style.setProperty('--hole-opacity',clamp((local-.55)/.3).toFixed(3));layer.style.setProperty('--believer-scale',(0.25+local*3.4).toFixed(3));layer.style.setProperty('--merch-scale',(0.35+local*2.7).toFixed(3));layer.style.setProperty('--light-scale',(0.15+local*5).toFixed(3));layer.style.setProperty('--sigil-scale',(0.28+local*1.6).toFixed(3));layer.style.setProperty('--think-opacity',clamp((local-.58)/.28).toFixed(3))});
const strength=document.querySelector('[data-exit-strength]');if(strength)strength.textContent=document.documentElement.classList.contains('signal-complete')?'100% // FULL SIGNAL':`${Math.round(10+p*70)}% // TUNING`;document.querySelectorAll('[data-live-strength]').forEach(el=>el.textContent=document.documentElement.classList.contains('signal-complete')?'100%':`${Math.round(10+p*70)}%`)}
let ticking=false;const queue=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{render();ticking=false})};addEventListener('scroll',queue,{passive:true});addEventListener('resize',queue);render();
const panel=document.querySelector('[data-control-panel]');document.querySelector('[data-control]')?.addEventListener('click',()=>{panel.hidden=!panel.hidden});document.querySelector('[data-control-close]')?.addEventListener('click',()=>panel.hidden=true);
const world=document.querySelector('[data-world-modal-panel]');document.querySelectorAll('[data-world-modal]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();world.hidden=false}));document.querySelector('[data-world-close]')?.addEventListener('click',()=>world.hidden=true);world?.addEventListener('click',e=>{if(e.target===world)world.hidden=true});
})();
